# Generated by Django 5.2.1 on 2025-05-18 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_uno', models.CharField(max_length=100)),
                ('apellido_dos', models.CharField(blank=True, max_length=100, null=True)),
                ('run', models.CharField(max_length=10)),
                ('dv', models.CharField(max_length=2)),
                ('fecha_nacimiento', models.DateField()),
                ('fono', models.IntegerField(blank=True, null=True)),
                ('fono_dos', models.IntegerField(blank=True, null=True)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicacion.comuna')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apoderado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apoderado',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_uno', models.CharField(max_length=100)),
                ('apellido_dos', models.CharField(blank=True, max_length=100, null=True)),
                ('run', models.CharField(max_length=10)),
                ('dv', models.CharField(max_length=2)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicacion.comuna')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profesor',
            },
        ),
    ]
